### ISSUE TITLE
Syntax error during execution

### ISSUE THREAD

**Issue by AhmedRedaAmin** [MrBenJ/wordlist-to-json#1]
So here is something interesting :
![selection_052](https://user-images.githubusercontent.com/17142710/46585799-d3e84880-ca75-11e8-8ec8-f8b677b290cb.png)
Haven't had time to look around to get a sense of what is doing what , but you may wanna try to tell me your setup , I guess ?

**Comment by MrBenJ** [comment]
What version of Node are you using?

**Comment by AhmedRedaAmin** [comment]
v 4.2.6
pretty hardcore legacy stuff here .

**Comment by MrBenJ** [comment]
That's your problem. Node version should be at minimum 8. It might work on version 6, but I wrote this on Node 8.

**Comment by MrBenJ** [comment]
@AhmedRedaAmin - No worries on using an older version of Node.

I'm using destructure syntax in this package, and that wasn't supported until later versions of Node v4. 

If you upgrade, I'm 99% sure that the package will work. Feel free to reference this issue if you want to make a README.md update :D
